[profile.default]
solc_version = '0.8.24'
src = "./contracts"
test = 'test'
script = 'script'
out = "./build"
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@Lazychain/solidity-contracts/=./',
    '@hyperlane-xyz/=node_modules/@hyperlane-xyz/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
evm_version = 'cancun'
extra_output = [
    "abi",
    "evm.bytecode",
    "evm.deployedBytecode",
    "evm.methodIdentifiers",
]
bytecode_hash = 'ipfs'
deny_warnings = true

# Optimizer
optimizer_runs = 200

# [model_checker]
# contracts = { "contracts/apps/lottery/Lottery.sol" = ["Lottery"] }
# engine = 'chc'
# timeout = 10000
# targets = ['assert']

# Testing
gas_limit = "18446744073709551615" # u64::MAX
gas_price = 0
threads = 0                        # zero specifies the number of logical cores.

[fuzz]
runs = 1000

[invariant]
runs = 1000
depth = 500

# Format
[fmt]
single_line_statement_blocks = 'multi'
multiline_func_header = 'attributes_first'
sort_imports = true
contract_new_lines = true
quote_style = 'double'

# Documentation
[doc]
out = 'docs'
title = 'Lazychain Smart Contract Documentation'
