name: checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  NODE_OPTIONS: --max_old_space_size=8192

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: npm run lint

  tests-foundry:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          submodules: recursive
          node-version: 20.x
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v3-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        shell: bash
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run Forge tests
        run: forge test -vvv
        env:
          # Only fuzz intensely if we're running this action on a push to main or for a PR going into main:
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'intense' }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run coverage
        run: npm run coverage
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: rm foundry.toml
      - uses: crytic/slither-action@v0.4.0
        with:
          node-version: 18.15
          slither-version: 0.10.1

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v2.1
        with:
          check_hidden: true
          check_filenames: true
          skip: package-lock.json,*.pdf,vendor
