on: [push]

name: Unit tests

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly-ca67d15f4abd46394b324c50e21e66f306a1162d"
      - name: Install deps
        run: forge install
      - name: Run tests
        run: forge test -vvv

      - name: Generate coverage report
        run: |
          forge coverage --report lcov
        id: coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./lcov.info # optional
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true

